name: admin
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev
publish_to: "none" 

# Versioning
version: 1.0.0+1

# Dart SDK version constraints
environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  fl_chart: ^0.62.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  gap: ^3.0.1
  get: ^4.6.6
  provider: ^6.1.2
  intl: ^0.20.1
  win32: ^5.5.4


# Developer dependencies for testing
dev_dependencies:
  flutter_test:
    sdk: flutter

# Dependency overrides to resolve transitive dependencies
dependency_overrides:
  characters: ^1.4.0
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  source_span: ^1.10.1
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  matcher: ^0.12.17
  stack_trace: ^1.12.1
  stream_channel: ^2.1.3
  test_api: ^0.7.4
  vm_service: ^15.0.0

# Flutter-specific configurations
flutter:
  # Enables Material Design
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/icons/
